### ISSUE TITLE
Install fails on ARCH during pip command

### ISSUE THREAD

**Issue by conhibit** [tiberiu44/TTS-Cube#52]
similar issue happens with Tortoise TTS installl...

My first attempt i may of installed it in a unusual directory from a previos app install... and it got a similar error...

[negatron@Negatron]-[~]
>>> git clone https://github.com/tiberiu44/TTS-Cube.git
Cloning into 'TTS-Cube'...
remote: Enumerating objects: 2345, done.
remote: Counting objects: 100% (958/958), done.
remote: Compressing objects: 100% (286/286), done.
remote: Total 2345 (delta 723), reused 897 (delta 672), pack-reused 1387
Receiving objects: 100% (2345/2345), 697.70 MiB | 1.30 MiB/s, done.
Resolving deltas: 100% (1553/1553), done.
Updating files: 100% (258/258), done.
[negatron@Negatron]-[~]
>>> cd TTS-Cube                                        
pip3 install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
Collecting numpy==1.15.0
  Using cached numpy-1.15.0.zip (4.5 MB)
  Preparing metadata (setup.py) ... done
Collecting librosa==0.6.1
  Using cached librosa-0.6.1.tar.gz (1.6 MB)
  Preparing metadata (setup.py) ... done
Collecting scipy==1.1.0
  Using cached scipy-1.1.0.tar.gz (15.6 MB)
  Preparing metadata (setup.py) ... done
Collecting pysptk==0.1.11
  Using cached pysptk-0.1.11.tar.gz (402 kB)
  Preparing metadata (setup.py) ... done
Collecting Cython==0.27.3
  Using cached Cython-0.27.3.tar.gz (1.8 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [50 lines of output]
      Unable to find pgen, not compiling formal grammar.
      running egg_info
      creating /tmp/pip-pip-egg-info-5nzjjh0x/Cython.egg-info
      writing /tmp/pip-pip-egg-info-5nzjjh0x/Cython.egg-info/PKG-INFO
      writing dependency_links to /tmp/pip-pip-egg-info-5nzjjh0x/Cython.egg-info/dependency_links.txt
      writing entry points to /tmp/pip-pip-egg-info-5nzjjh0x/Cython.egg-info/entry_points.txt
      writing top-level names to /tmp/pip-pip-egg-info-5nzjjh0x/Cython.egg-info/top_level.txt
      writing manifest file '/tmp/pip-pip-egg-info-5nzjjh0x/Cython.egg-info/SOURCES.txt'
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-f_dvzi41/cython_59458e29aa504995a3935636c2cacd7a/setup.py", line 229, in <module>
          setup(
        File "/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/usr/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/usr/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/usr/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/usr/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/usr/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 308, in run
          self.find_sources()
        File "/usr/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 316, in find_sources
          mm.run()
        File "/usr/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 560, in run
          self.add_defaults()
        File "/usr/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 597, in add_defaults
          sdist.add_defaults(self)
        File "/usr/lib/python3.10/site-packages/setuptools/command/sdist.py", line 106, in add_defaults
          super().add_defaults()
        File "/usr/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 252, in add_defaults
          self._add_defaults_ext()
        File "/usr/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
          build_ext = self.get_finalized_command('build_ext')
        File "/usr/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 305, in get_finalized_command
          cmd_obj.ensure_finalized()
        File "/usr/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
          self.finalize_options()
        File "/tmp/pip-install-f_dvzi41/cython_59458e29aa504995a3935636c2cacd7a/Cython/Distutils/build_ext.py", line 18, in finalize_options
          self.distribution.ext_modules[:] = cythonize(
        File "/tmp/pip-install-f_dvzi41/cython_59458e29aa504995a3935636c2cacd7a/Cython/Build/Dependencies.py", line 913, in cythonize
          module_list, module_metadata = create_extension_list(
        File "/tmp/pip-install-f_dvzi41/cython_59458e29aa504995a3935636c2cacd7a/Cython/Build/Dependencies.py", line 742, in create_extension_list
          elif isinstance(patterns, basestring) or not isinstance(patterns, collections.Iterable):
      AttributeError: module 'collections' has no attribute 'Iterable'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
[negatron@Negatron]-[~/TTS-Cube]
>>> cd TTS-Cube
sudo pip3 install -r requirements.txt
cd: no such file or directory: TTS-Cube
[sudo] password for negatron: 
Collecting numpy==1.15.0
  Downloading numpy-1.15.0.zip (4.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 1.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting librosa==0.6.1
  Downloading librosa-0.6.1.tar.gz (1.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 527.5 kB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting scipy==1.1.0
  Downloading scipy-1.1.0.tar.gz (15.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.6/15.6 MB 1.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting pysptk==0.1.11
  Downloading pysptk-0.1.11.tar.gz (402 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 402.5/402.5 kB 253.1 kB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting Cython==0.27.3
  Downloading Cython-0.27.3.tar.gz (1.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 1.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [50 lines of output]
      Unable to find pgen, not compiling formal grammar.
      running egg_info
      creating /tmp/pip-pip-egg-info-nrfid8ec/Cython.egg-info
      writing /tmp/pip-pip-egg-info-nrfid8ec/Cython.egg-info/PKG-INFO
      writing dependency_links to /tmp/pip-pip-egg-info-nrfid8ec/Cython.egg-info/dependency_links.txt
      writing entry points to /tmp/pip-pip-egg-info-nrfid8ec/Cython.egg-info/entry_points.txt
      writing top-level names to /tmp/pip-pip-egg-info-nrfid8ec/Cython.egg-info/top_level.txt
      writing manifest file '/tmp/pip-pip-egg-info-nrfid8ec/Cython.egg-info/SOURCES.txt'
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-3w_rwq84/cython_2213ce863fd24e27ae02ae2fbe17f21d/setup.py", line 229, in <module>
          setup(
        File "/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/usr/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/usr/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/usr/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/usr/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/usr/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 308, in run
          self.find_sources()
        File "/usr/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 316, in find_sources
          mm.run()
        File "/usr/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 560, in run
          self.add_defaults()
        File "/usr/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 597, in add_defaults
          sdist.add_defaults(self)
        File "/usr/lib/python3.10/site-packages/setuptools/command/sdist.py", line 106, in add_defaults
          super().add_defaults()
        File "/usr/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 252, in add_defaults
          self._add_defaults_ext()
        File "/usr/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
          build_ext = self.get_finalized_command('build_ext')
        File "/usr/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 305, in get_finalized_command
          cmd_obj.ensure_finalized()
        File "/usr/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
          self.finalize_options()
        File "/tmp/pip-install-3w_rwq84/cython_2213ce863fd24e27ae02ae2fbe17f21d/Cython/Distutils/build_ext.py", line 18, in finalize_options
          self.distribution.ext_modules[:] = cythonize(
        File "/tmp/pip-install-3w_rwq84/cython_2213ce863fd24e27ae02ae2fbe17f21d/Cython/Build/Dependencies.py", line 913, in cythonize
          module_list, module_metadata = create_extension_list(
        File "/tmp/pip-install-3w_rwq84/cython_2213ce863fd24e27ae02ae2fbe17f21d/Cython/Build/Dependencies.py", line 742, in create_extension_list
          elif isinstance(patterns, basestring) or not isinstance(patterns, collections.Iterable):
      AttributeError: module 'collections' has no attribute 'Iterable'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
[negatron@Negatron]-[~/TTS-Cube]
>>>

**Comment by tiberiu44** [comment]
Hi @conhibit ,

I know about the installation issues with the current main branch and I'm curently working on version 2.0, which has a better vocoder and integrates with a pretrained language model for better prosody. I'll let you know as soon as it's ready, but until then, I'm unable to provide any support for the previous branch, because it depends on a lot of obsolete packages.
